M48
; DRILL file {KiCad 7.0.8} date Tue Apr 30 13:20:52 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-30T13:20:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.1Y-3.2
X6.1Y-3.4
T2
X5.8Y-3.1
X5.8Y-3.2
X6.4Y-3.2
X6.5Y-3.2
T0
M30
